version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  before-install:
    executor:
      name: node/default
    docker:
      - image: docker:latest
    steps:
      - checkout
      - run:
          name: Build Docker Image
          command: |
            docker build -t siky98/docker-training -f Dockerfile.dev .
workflows:
  deploy-server:
    jobs:
      - before-install