version: 2.1
jobs:
  before-install:
    machine: true
    steps:
      - checkout
      - run:
          name: Build Docker Dev Image
          command: |
            docker build -t siky98/docker-training-dev -f Dockerfile.dev .
      - run:
          name: Run Tests
          command: |
            docker run -e CI=true siky98/docker-training-dev npm run test -- --coverage
      - run:
          name: Build Docker Prod Image
          command: |
            docker build -t siky98/docker-training-prod .
      - run:
          name: Cache Docker Image In Workspace
          command: |
            mkdir -p docker-workspace
            docker save -o docker-workspace/docker-training.tar siky98/docker-training-prod
      - persist_to_workspace:
          root: docker-workspace
          paths:
            - docker-training.tar
  deploy:
    machine: true
    steps:
      - attach_workspace:
          at: /tmp/docker-workspace
      - run:
          name: Installs SSH Pass Service
          command: |
            sudo apt-get update
            sudo apt-get install sshpass
      - run:
          name: Lists Docker Workspace Directory
          command: |
            ls /tmp/docker-workspace/
      - run:
          name: Upload Cached Docker Images
          command: |
            sshpass -p "${SERVER_PASS}" scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -r /tmp/docker-workspace/docker-training.tar root@167.71.138.216:workspace
            sshpass -p "${SERVER_PASS}" scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -r /tmp/docker-workspace/docker-training.tar root@178.128.172.24:workspace
            sshpass -p "${SERVER_PASS}" scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -r /tmp/docker-workspace/docker-training.tar root@209.97.139.14:workspace
      - run:
          name: Remove Docker Images
          command: |
            sshpass -p "${SERVER_PASS}" ssh root@167.71.138.216 -oStrictHostKeyChecking=no "docker image rm siky98/docker-training-prod || true"
            sshpass -p "${SERVER_PASS}" ssh root@178.128.172.24 -oStrictHostKeyChecking=no "docker image rm siky98/docker-training-prod || true"
            sshpass -p "${SERVER_PASS}" ssh root@209.97.139.14 -oStrictHostKeyChecking=no "docker image rm siky98/docker-training-prod || true"
      - run:
          name: Stop and Remove Running Docker Containers
          command: |
            sshpass -p "${SERVER_PASS}" ssh root@167.71.138.216 -oStrictHostKeyChecking=no "docker stop docker-training-prod || true && docker rm docker-training-prod || true"
            sshpass -p "${SERVER_PASS}" ssh root@178.128.172.24 -oStrictHostKeyChecking=no "docker stop docker-training-prod || true && docker rm docker-training-prod || true"
            sshpass -p "${SERVER_PASS}" ssh root@209.97.139.14 -oStrictHostKeyChecking=no "docker stop docker-training-prod || true && docker rm docker-training-prod || true"
      - run:
          name: Load and Run Cached Docker Image
          command: |
            sshpass -p "${SERVER_PASS}" ssh root@167.71.138.216 -oStrictHostKeyChecking=no "docker load < /root/workspace && docker run -d --name docker-training-prod -p 80:80 siky98/docker-training-prod"
            sshpass -p "${SERVER_PASS}" ssh root@178.128.172.24 -oStrictHostKeyChecking=no "docker load < /root/workspace && docker run -d --name docker-training-prod -p 80:80 siky98/docker-training-prod"
            sshpass -p "${SERVER_PASS}" ssh root@209.97.139.14 -oStrictHostKeyChecking=no "docker load < /root/workspace && docker run -d --name docker-training-prod -p 80:80 siky98/docker-training-prod"
workflows:
  deploy-server:
    jobs:
      - before-install
      - deploy:
          requires:
            - before-install